name = "passkey"
main = "src/index.ts"
compatibility_date = "2024-11-05"

# compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "passkey2"
database_id = "ccc67ae2-b200-4ee9-8103-6901ad73eeae"

[triggers]
crons = ["0 0 * * *"]

[observability]
enabled = true
head_sampling_rate = 1

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [ai]
# binding = "AI"

